title: Jagadesh Rao — FPGA & Embedded Systems
description: "Notes on FPGA design, high-speed digital interfaces, and embedded systems."
author: Jagadesh Rao Rudrapankte

baseurl: ""
url: "https://jagadeshrao.github.io"

collections:
  pages:
    output: true
    permalink: /:collection/:name/

plugins:
  - jekyll-feed
